# Generated by Django 3.1.1 on 2020-09-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_saved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
