# Generated by Django 3.1.1 on 2020-10-02 05:31

import connect.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201002_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=connect.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
